version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather
    env_file:
      - ./.env.yaml
    ports:
      - "80:80"
    volumes:
      - .:/go/src/app
    tty: true
    